config/routes.rb
UbiqueArt::Application.routes.draw do
  match '/help', to: 'static_pages#help'
  match '/impressum', to: 'static_pages#impressum'
  match '/about', to: 'static_pages#index'
  
  resources :painting_at_spots


  resources :spots


  resources :tag_categories


  resources :tags


  resources :artist_profiles


  resources :paintings


  root :to => "static_pages#index" # landing page
  devise_for :users
  resources :users 
  
  match '/users/:id/like/:painting_id' => 'users#like'
  match '/users/:id/unlike/:painting_id' => 'users#unlike'
  match '/paintings/:id/qr_png' => 'paintings#qr_png'
  match '/paintings/:id/qr_download' => 'paintings#qr_download'
    
end

app/models/painting.rb
class Painting < ActiveRecord::Base
  attr_accessible :description, :name, :image
  belongs_to :artist_profile

  has_and_belongs_to_many :tags
  has_and_belongs_to_many :liked_by, :class_name=>'User', :join_table => "painting_likes"

  has_many :spots,
    class_name: PaintingAtSpot.name.to_s

   mount_uploader :image, PaintingUploader
   
   validates :artist_profile_id, presence: true
end

app/controllers/paintings_controller.rb
class PaintingsController < ApplicationController
  respond_to :html
  require 'rqrcode'
  # GET /paintings
  def index
    @paintings = Painting.scoped
  end

  # GET /paintings/1
  def show
    authorize! :show, painting
    if (params[:spotted]=='true') # TODO
      @spotted = true
    end
  end

  # GET /paintings/new
  def new
    @painting = Painting.new
    authorize! :new, painting
  end

  # GET /paintings/1/edit
  def edit
    authorize! :edit, painting
  end

  # POST /paintings
  def create
    @painting = Painting.new(params[:painting])
    authorize! :create, painting
    
    painting.artist_profile = current_user.artist_profile

    if @painting.save
      redirect_to action: :index, notice: 'Bild angelegt.'
    else
      render action: "new"
    end
  end

  # PUT /paintings/1
  def update
    authorize! :update, painting

    if painting.update_attributes(params[:painting])
      redirect_to paintings_path, notice: 'Bilddaten aktualisiert.'
    else
      Rails.logger.debug painting.errors.to_yaml
      render action: :edit
    end
  end

  # DELETE /paintings/1
  def destroy
    authorize! :destroy, painting
    @painting.destroy

    redirect_to paintings_url
  end
  
  def qr
    render :layout => false
  end
  
  def qr_png # TODO only once, store image @S3
    size = Integer(params[:size]) || 10
    @qr = gen_qr
    image = ChunkyPNG::Image.new(size * @qr.modules.size, size * @qr.modules.size,
                  ChunkyPNG::Color::WHITE)
    @qr.modules.each_index do |x|
      @qr.modules.each_index do |y|
        if (@qr.dark?(x,y))
          image.rect(x * size, y * size, (x * size) + size, (y * size) + size, 
            ChunkyPNG::Color::BLACK, ChunkyPNG::Color::BLACK)
        end
      end
    end
    send_data(image , :filename => "qrcode.png", :type=>"image/png")
  end
  
  def qr_download
    @no_footer = true
  end

  private
  
  def gen_qr
    RQRCode::QRCode.new(painting_url(painting)+'&spotted=true', size:7)
  end
  helper_method :gen_qr
  
  def painting
    return @painting ||= Painting.find(params.fetch(:id))
  end
  helper_method :painting

  def paintings
    return @paintings
  end
  helper_method :paintings
end

app/helpers/paintings_helper.rb
module PaintingsHelper
end

app/views/paintings/_form.haml
= form_for(painting) do |f|
  .row
    .large-6.columns
      = f.label "Name"
      = f.text_field :name
    .large-6.columns
      = f.label "Beschreibung"
      = f.text_area :description
  .row
    .large-12.columns
      = f.label "Bilddatei"
      = f.file_field :image
  %p
  .form-actions
    = f.submit 'Speichern', class: 'button radius'
    oder
    = link_to 'zurück', paintings_path, class: 'radius button small alert'

app/views/paintings/_grid.haml
#gallery.row
  .large-12.columns
    %ul.large-block-grid-4
      - paintings.in_groups_of(4).each do |group|
        - group.each do |painting|
          %li
            - if painting.present?
              = image_tag painting.image.gallery.url
              .overlay
                %span
                  %h3
                    = link_to painting.name, painting
                .artist
                  von
                  = link_to painting.artist_profile.user.name, painting.artist_profile
                .description
                  = painting.description
                .actions
                  %ul.button-group.radius
                    - # TODO: render 'users/like', painting: painting.id
                    - if can? :like, painting and not current_user.liked_paintings.include? painting
                      %li
                        = link_to "Like", {controller: :users, action: :like, id: current_user.id, painting_id: painting.id}, class: 'button small'
                          
                    - if can? :unlike, painting and current_user.liked_paintings.include? painting
                      %li
                        = link_to "Unlike", {controller: :users, action: :unlike, id: current_user.id, painting_id: painting.id}, class: 'button small secondary'
                          
                    - if can?(:edit, painting)
                      %li
                        = link_to edit_painting_path(painting), class: 'button small' do
                          %i.fi-edit
                    - if can?(:destroy, painting)
                      %li
                        = link_to painting_path(painting), method: :delete, class: 'button small', confirm: 'Sind Sie Sicher?' do
                          %i.fi-trash

app/views/paintings/_qr.haml
= stylesheet_link_tag "qrcode_table", :media => "all"
- @qr = gen_qr
%table.qr
  - @qr.modules.each_index do |x|
    %tr.qr
    - @qr.modules.each_index do |y|
      - if @qr.dark?(x,y)
        %td.black
      - else
        %td.white

app/views/paintings/edit.haml
= provide(:title, "Werkseite bearbeiten")
= render 'form'

app/views/paintings/index.haml
= provide(:title, "Werke")
= render 'grid'
%br
- if can? :create, Painting
  = link_to new_painting_path, class: 'button radius small', title: 'Neues Kunstwerk eintragen' do
    %i.fi-plus

app/views/paintings/new.haml
= provide(:title, "Kunstwerk eintragen")
= render 'form'

app/views/paintings/qr_download.haml
%h6 QR-Code downloaden  
= form_tag url_for( controller: :paintings, action: :qr_png, painting_id: painting.id) do
  = radio_button_tag(:size, "3") 
  = label_tag(:size_small, "Klein") 
  = radio_button_tag(:size, "6", checked = true) 
  = label_tag(:age_adult, "Mittel")
  = radio_button_tag(:size, "12")
  = label_tag(:age_adult, "Groß")
  = radio_button_tag(:size, "25")
  = label_tag(:age_adult, "Riesig")
  = submit_tag "Download", class: "button radius small"

app/views/paintings/show.haml
= provide(:title, painting.name)
%p
  - if can? :edit, painting
    = link_to 'Bearbeiten', edit_painting_path(@painting), class: 'button small'
  = render 'users/like'
-if @spotted == true
  .row 
    %h2 
      spotted
.row
  .large-4.columns
    = link_to image_tag(painting.image.gallery.url), painting.image.url, :class => 'fancybox', :remote => true
  .large-8.columns
    - if painting.liked_by.any?
      %i
        = painting.liked_by.count
        likes
    - else
      %i
        Dieses Bild hat noch keine likes
    %h5 Kurzinfo:
    = painting.description
.row
%p
.row
  .large-1.columns
    = link_to image_tag(url_for controller: :paintings, action: :qr_png, painting_id: painting.id, size: 3), url_for( controller: :paintings, action: :qr_download, painting_id: painting.id), remote: true, class: 'fancybox'
  .large-3.columns
    %h6= link_to "QR-Code downloaden", url_for(controller: :paintings, action: :qr_download, painting_id: painting.id), remote: true, class: 'fancybox' 
    
  .large-8.columns