config/routes.rb
UbiqueArt::Application.routes.draw do
  match '/help', to: 'static_pages#help'
  match '/impressum', to: 'static_pages#impressum'
  match '/about', to: 'static_pages#index'
  
  resources :painting_at_spots


  resources :spots


  resources :tag_categories


  resources :tags


  resources :artist_profiles


  resources :paintings


  root :to => "static_pages#index" # landing page
  devise_for :users
  resources :users 
  
  match '/users/:id/like/:painting_id' => 'users#like'
  match '/users/:id/unlike/:painting_id' => 'users#unlike'
  match '/paintings/:id/qr_png' => 'paintings#qr_png'
  match '/paintings/:id/qr_download' => 'paintings#qr_download'
    
end

app/models/painting_at_spot.rb
class PaintingAtSpot < ActiveRecord::Base
  attr_accessible :from_date, :to_date
  belongs_to :painting
  belongs_to :spot
  has_and_belongs_to_many :scanned_by, :class_name=>'User', :join_table => "scans"
end

app/controllers/painting_at_spots_controller.rb
class PaintingAtSpotsController < ApplicationController
  # GET /painting_at_spots
  # GET /painting_at_spots.json
  def index
    @painting_at_spots = PaintingAtSpot.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @painting_at_spots }
    end
  end

  # GET /painting_at_spots/1
  # GET /painting_at_spots/1.json
  def show
    @painting_at_spot = PaintingAtSpot.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @painting_at_spot }
    end
  end

  # GET /painting_at_spots/new
  # GET /painting_at_spots/new.json
  def new
    @painting_at_spot = PaintingAtSpot.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @painting_at_spot }
    end
  end

  # GET /painting_at_spots/1/edit
  def edit
    @painting_at_spot = PaintingAtSpot.find(params[:id])
  end

  # POST /painting_at_spots
  # POST /painting_at_spots.json
  def create
    @painting_at_spot = PaintingAtSpot.new(params[:painting_at_spot])

    respond_to do |format|
      if @painting_at_spot.save
        format.html { redirect_to @painting_at_spot, notice: 'Painting at spot was successfully created.' }
        format.json { render json: @painting_at_spot, status: :created, location: @painting_at_spot }
      else
        format.html { render action: "new" }
        format.json { render json: @painting_at_spot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /painting_at_spots/1
  # PUT /painting_at_spots/1.json
  def update
    @painting_at_spot = PaintingAtSpot.find(params[:id])

    respond_to do |format|
      if @painting_at_spot.update_attributes(params[:painting_at_spot])
        format.html { redirect_to @painting_at_spot, notice: 'Painting at spot was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @painting_at_spot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /painting_at_spots/1
  # DELETE /painting_at_spots/1.json
  def destroy
    @painting_at_spot = PaintingAtSpot.find(params[:id])
    @painting_at_spot.destroy

    respond_to do |format|
      format.html { redirect_to painting_at_spots_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/painting_at_spots_helper.rb
module PaintingAtSpotsHelper
end

app/views/painting_at_spots/_form.html.erb
<%= simple_form_for(@painting_at_spot) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :from_date%>
    <%= f.input :to_date %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Eintragen"%>
  </div>
<% end %>

app/views/painting_at_spots/edit.html.erb
<h1>Platzierung bearbeiten</h1>

<%= render 'form' %>

<%= link_to 'Anzeigen', @painting_at_spot %> |
<%= link_to 'Zurück', painting_at_spots_path %>

app/views/painting_at_spots/index.html.erb
<h1>Platzierungen</h1>

<table>
  <tr>
    <th>Werk</th>
    <th>Künstler</th>
		<th>Spot</th>
    <th>Ab</th>
    <th>Bis</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @painting_at_spots.each do |painting_at_spot| %>
  <tr>
    <td><%= link_to painting_at_spot.painting.name, painting_at_spot.painting %></td>
    <td><%= link_to painting_at_spot.painting.artist_profile.user.name, painting_at_spot.painting.artist_profile %></td>
		<td><%= link_to painting_at_spot.spot.name, painting_at_spot.spot %></td>
		<td><%= painting_at_spot.from_date %></td>
		<td><%= painting_at_spot.to_date %></td>
			<td><%= link_to 'Anzeigen', painting_at_spot %></td>
		<% if can? :edit, painting_at_spot then %>
    	<td><%= link_to 'Bearbeiten', edit_painting_at_spot_path(painting_at_spot) %></td>
		<% end %>
		<% if can? :delete, painting_at_spot then %>
    	<td><%= link_to 'Löschen', painting_at_spot, method: :delete, data: { confirm: 'Sicher?' } %></td>
		<% end %>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Neue Platzierung eintragen', new_painting_at_spot_path %>

app/views/painting_at_spots/new.html.erb
<h1>Neue Platzierung eintragen</h1>

<%= render 'form' %>

<%= link_to 'Zurück', painting_at_spots_path %>

app/views/painting_at_spots/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Ab:</b>
  <%= @painting_at_spot.from_date %>
</p>

<p>
  <b>Bis:</b>
  <%= @painting_at_spot.to_date %>
</p>


<%= link_to 'Bearbeiten', edit_painting_at_spot_path(@painting_at_spot) %> |
<%= link_to 'Zurück', painting_at_spots_path %>