config/routes.rb
UbiqueArt::Application.routes.draw do
  match '/help', to: 'static_pages#help'
  match '/impressum', to: 'static_pages#impressum'
  match '/about', to: 'static_pages#index'
  
  resources :painting_at_spots


  resources :spots


  resources :tag_categories


  resources :tags


  resources :artist_profiles


  resources :paintings


  root :to => "static_pages#index" # landing page
  devise_for :users
  resources :users 
  
  match '/users/:id/like/:painting_id' => 'users#like'
  match '/users/:id/unlike/:painting_id' => 'users#unlike'
  match '/paintings/:id/qr_png' => 'paintings#qr_png'
  match '/paintings/:id/qr_download' => 'paintings#qr_download'
    
end

app/views/layouts/_header.html.erb
<%= link_to "Ubique Art", root_path, :class => 'brand' %>
<ul class="nav">
  <% if user_signed_in? %>
    <li>
    <%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %>
    </li>
  <% else %>
    <li>
    <%= link_to 'Login', new_user_session_path %>
    </li>
  <% end %>
  <% if user_signed_in? %>
    <li>
    <%= link_to 'Edit account', edit_user_registration_path %>
    </li>
    <% if current_user.has_role? :admin %>
      <li>
      <%= link_to 'Admin', users_path %>
      </li>
    <% end %>
  <% else %>
    <li>
    <%= link_to 'Sign up', new_user_registration_path %>
    </li>
  <% end %>
</ul>

app/views/layouts/_messages.html.erb
<div class="container">
<div class="row">
  <div class="twelve columns">
    <% if flash[:error] %>
      <%= content_tag :div, :id => "flash_name", :class => "alert-box error" do %>
        <%= flash[:error] %>
        <a class="close">x</a>
      <% end %>
    <% end %>

    <% if flash[:notice] %>
      <%= content_tag :div, :id => "flash_name", :class => "alert-box success" do %>
        <%= flash[:notice] %>
        <a class="close">x</a>
      <% end %>
    <% end %>

    <% if flash[:alert] %>
      <%= content_tag :div, :id => "flash_name", :class => "alert-box alert" do %>
        <%= flash[:alert] %>
        <a class="close">x</a>
      <% end %>
    <% end %>
    
  </div><!-- //.twelve.columns -->
</div><!-- //.row -->
</div><!-- //.container -->

app/views/layouts/_navigation.haml
.fixed
  .contain-to-grid
    %nav.top-bar
      %ul.title-area
        %li.name
          %h1
            = link_to root_path, title: 'ubique art' do
              = image_tag 'logo.png', style: 'padding-top: 10px;'
        %li.toggle-topbar.menu-icon
          = link_to '#' do
            %span Menu
          /
      %section.top-bar-section
        %ul.left
          %li.divider
          %li
            = link_to 'Artists', artist_profiles_path
          %li.divider
          %li
            = link_to 'Spots', spots_path
          %li.divider
          %li
            = link_to 'Werke', paintings_path
          %li.divider
          %li
            = link_to 'Mitglieder', users_path
          %li.divider

        %ul.right
          - if user_signed_in?
            %li.divider
            %li
              = link_to 'Profil', current_user
            %li.divider
            - if current_user.admin?
              %li
                = link_to 'Admin', users_path
          - if user_signed_in?
            %li
              = link_to 'Abmelden', destroy_user_session_path, :method=>'delete', class: 'alert'
          - else
            %li
              = link_to 'Anmelden', new_user_session_path, class: 'success'

app/views/layouts/application.haml
!!!
%html
  - @title = content_for?(:title) ? ">> #{yield(:title)}" : ""
  %head
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %title ubique art #{@title}
    %meta{:content => content_for?(:description) ? yield(:description) : "ubique art", :name => "description"}/
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    = javascript_include_tag "vendor/custom.modernizr"
    = csrf_meta_tags
    = yield(:head)
  %body{:class => "#{controller_name} #{action_name}"}
    #wrap
      = render 'layouts/navigation'

      #main{:role => "main"}
        -if current_page?(root_path)
          = render '/layouts/messages'
          = yield
        -else
          .row
            .small-12.large-12.columns
              = render '/layouts/messages'
              - if @title.length
                %h2 
                  %span.heading= @title
              = yield
    %footer
      - unless @no_footer
        #{link_to "Impressum", "/impressum"} | #{link_to "Über ubique art", "/#about"} | Entwickelt mit Unterstützung von #{link_to 'starterkitchen.de', 'http://starterkitchen.de'}
    = yield :scripts